### ISSUE TITLE
The Code stop working when trying to access to OpenSea

### ISSUE THREAD

**Issue by Nikname-choose-1** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#23]
when the metamask wallet is connected and linked on the chrome browser, the Opensea page is charged but there is a problem. As the interface with the different wallets you can use to login appear the code stop working with an error that say (Symbol[0000000000])

**Comment by alegr44** [comment]
I get stuck with the cloudflare validation...

**Comment by shirazdelhi** [comment]
Yeah Same with me

**Comment by Markkevin052** [comment]
same here

**Comment by Markkevin052** [comment]
actually its not the problem of code bro

when it clicks on metamask opensea login its opening the metamask extension install page but according to program it should login directly so..... 
its getting stuck

can any programmer solve this?

**Comment by tusharhrb** [comment]
actually i manually tried .... instead of first clicking on metamask in 'connect your wallet' ..... if you first click on 'show more options' and then click on metamask the next auto process will be similar to that he showed in the video ..... i dont know how to do that but if anyone knows please do it .....

**Comment by nftdevs** [comment]
Please get the latest version of the code.
